{% set version = "4.27.3" %}

package:
  name: gen3
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/gen3/gen3-{{ version }}.tar.gz
  sha256: 252b4e63285ef41b08d0bc9046616c35586c48d0a59291caf28f384090738a9a

build:
  entry_points:
    - gen3 = gen3.cli.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ={{ python_min }}
    - poetry >=1.4.1
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - indexclient >=2.3.0,<3.0.0
    - drsclient >=0.3.0
    - aiohttp
    - backoff
    - cdislogging >=1.1.0,<2.0.0
    - click
    - fhirclient
    - jsonschema
    - dataclasses-json <=0.5.9
    # - pypfb >=0.5.30
    - tqdm >=4.61.2,<5.0.0
    - humanfriendly
    - python-dateutil
    - aiofiles >=0.8.0,<0.9.0
    - pandas >=1.4.2
    - urllib3 >2.0.0
    - httpx
    - xmltodict >=0.13.0,<0.14.0
    - pyyaml >=6.0.1
    - gen3users

test:
  imports:
    - gen3
  commands:
    # - pip check
    # - gen3 --help
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://gen3.org/
  summary: Gen3 CLI and Python SDK
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - danielnachun
